
/*数目录*/
var tree='<div class="tree">';
tree+='<ul>';
tree+='<li class="tree-one">';
tree+='<p>一</p>';
tree+='<dl>';
tree+='<dt>第一章 机器人拆装基础知识介绍</dt>';
tree+='<dd>';
tree+='<p>★ 1.1 工业机器人常用传动机构及工作原理</p>';
tree+='<div>';
tree+='<a href="../1_1_1/1_1_1.html">◆ 1.1.1 机械传动之带传动</a>';
tree+='<a href="../1_1_2/1_1_2.html">◆ 1.1.2 机械传动之链传动</a>';
tree+='<a href="../1_1_3/1_1_3.html">◆ 1.1.3 机械传动之齿轮传动</a>';
tree+='<a href="../1_1_4/1_1_4.html">◆ 1.1.4 机械传动之螺旋传动</a>';
tree+='<a href="../1_1_5/1_1_5.html">◆ 1.1.5 机械传动之蜗杆传动</a>';
tree+='</div>';
tree+='</dd>';
tree+='<dd>';
tree+='<p>★ 1.2 工业机器人常用的驱动装置</p>';
tree+='<div>';
tree+='<a href="../1_2_1/1_2_1.html">◆ 1.2.1 电动驱动</a>';
tree+='<a href="../1_2_2/1_2_2.html">◆ 1.2.2 液压驱动</a>';
tree+='<a href="../1_2_3/1_2_3.html">◆ 1.2.3 气动驱动</a>';
tree+='</div>';
tree+='</dd>';
tree+='<dd>';
tree+='<p>★ 1.3 工业机器人传感器</p>';
tree+='<div>';
tree+='<a href="../1_3_1/1_3_1.html">◆ 1.3.1 传感器的定义及性能指标</a>';
tree+='<a href="../1_3_2/1_3_2.html">◆ 1.3.2 位置传感器</a>';
tree+='<a href="../1_3_3/1_3_3.html">◆ 1.3.3 速度传感器</a>';
tree+='<a href="../1_3_4/1_3_4.html">◆ 1.3.4 力或力矩传感器</a>';
tree+='<a href="../1_3_5/1_3_5.html">◆ 1.3.5 触觉传感器</a>';
tree+='<a href="../1_3_6/1_3_6.html">◆ 1.3.6 接近传感器</a>';
tree+='</div>';
tree+='</dd>';
tree+='<dd>';
tree+='<p>★ 1.4 机器人装配中常用工具的介绍</p>';
tree+='<div>';
tree+='<a href="../1_4_1/1_4_1.html">◆ 1.4.1 机器人机械部分拆装常用工具</a>';
tree+='<a href="../1_4_2/1_4_2.html">◆ 1.4.2 机器人电气系统拆装常用工具</a>';
tree+='</div>';
tree+='</dd>';
tree+='<dd>';
tree+='<p>★ 1.5 机器人装配中的注意事项</p>';
tree+='<div>';
tree+='<a href="../1_5_1/1_5_1.html">◆ 1.5.1 机器人机械系统拆装注意事项</a>';
tree+='<a href="../1_5_2/1_5_2.html">◆ 1.5.2 机器人电气系统拆装注意事项</a>';
tree+='</div>';
tree+='<p><a href="../1_6_1/1_6_1.html">★ 章节测试</a></p>';
tree+='</dd>';
tree+='</dl>';
tree+='</li>';
tree+='<li class="tree-one">';
tree+='<p>二</p>';
tree+='<dl>';
tree+='<dt>第二章 圆柱坐标机器人的装配与调试</dt>';
tree+='<dd>';
tree+='<p><a href="../2_0_1/2_0_1.html">★ 本章导入</a></p>';
tree+='</dd>';
tree+='<dd>';
tree+='<p>★ 2.1 圆柱坐标机器人简介</p>';
tree+='<div>';
tree+='<a href="../2_1_1/2_1_1.html">◆ 2.1.1 什么是圆柱坐标机器人</a>';
tree+='<a href="../2_1_2/2_1_2.html">◆ 2.1.2 圆柱坐标机器人的结构及功能</a>';
tree+='</div>';
tree+='</dd>';
tree+='<dd>';
tree+='<p>★ 2.2 机械传动部分的装配与调试</p>';
tree+='<div>';
tree+='<a href="../2_2_1/2_2_1.html">◆ 2.2.1 RV减速器</a>';
tree+='<a href="../2_2_2/2_2_2.html">◆ 2.2.2 线性滑轨</a>';
tree+='<a href="../2_2_3/2_2_3.html">◆ 2.2.3 滚珠丝杆</a>';
tree+='</div>';
tree+='</dd>';
tree+='<dd>';
tree+='<p>★ 2.3 圆柱坐标机器人本体的安装和调试</p>';
tree+='<div>';
tree+='<a href="../2_3_1/2_3_1.html">◆ 2.3.1 安装过程中需要的零部件和工量具</a>';
tree+='<a href="../2_3_2/2_3_2.html">◆ 2.3.2 底座的安装和调试</a>';
tree+='<a href="../2_3_3/2_3_3.html">◆ 2.3.3 立柱的安装和调试</a>';
tree+='<a href="../2_3_4/2_3_4.html">◆ 2.3.4 悬臂的安装</a>';
tree+='</div>';
tree+='</dd>';
tree+='<dd>';
tree+='<p><a href="../2_4_1/2_4_1.html">★ 2.4 圆柱坐标机器人电气系统的装配与调试</a></p>';
tree+='</dd>';
tree+='<dd>';
tree+='<p>★ 2.5 圆柱坐标机器人整机安装、调试与检查</p>';
tree+='<div>';
tree+='<a href="../2_5_1/2_5_1.html">◆ 2.5.1 伺服电动机驱动器参数设置</a>';
tree+='<a href="../2_5_2/2_5_2.html">◆ 2.5.2 示教器设置</a>';
tree+='<a href="../2_5_3/2_5_3.html">◆ 2.5.3 PLC程序下载</a>';
tree+='<a href="../2_5_4/2_5_4.html">◆ 2.5.4 最终检测</a>';
tree+='</div>';
tree+='<p><a href="../2_6_1/2_6_1.html">★ 章节测试</a></p>';
tree+='</dd>';
tree+='</dl>';
tree+='</li>';
tree+='<li class="tree-one">';
tree+='<p>三</p>';
tree+='<dl>';
tree+='<dt>第三章 直角坐标机器人的装配与调试</dt>';
tree+='<dd>';
tree+='<p><a href="../3_0_1/3_0_1.html">★ 本章导入</a></p>';
tree+='</dd>';
tree+='<dd>';
tree+='<p>★ 3.1 直角坐标机器人的简介</p>';
tree+='<div>';
tree+='<a href="../3_1_1/3_1_1.html">◆ 3.1.1 什么是直角坐标机器人</a>';
tree+='<a href="../3_1_2/3_1_2.html">◆ 3.1.2 直角坐标机器人的结构及功能</a>';
tree+='</div>';
tree+='</dd>';
tree+='<dd>';
tree+='<p>★ 3.2 机械传动部分的装配与调试</p>';
tree+='<div>';
tree+='<a href="../3_2_1/3_2_1.html">◆ 3.2.1 同步带</a>';
tree+='<a href="../3_2_2/3_2_2.html">◆ 3.2.2 行星减速器</a>';
tree+='</div>';
tree+='</dd>';
tree+='<dd>';
tree+='<p>★ 3.3 直角坐标机器人的安装与调试</p>';
tree+='<div>';
tree+='<a href="../3_3_1/3_3_1.html">◆ 3.3.1 工具、量具和本体零部件的准备</a>';
tree+='<a href="../3_3_2/3_3_2.html">◆ 3.3.2 W轴安装与检测</a>';
tree+='<a href="../3_3_3/3_3_3.html">◆ 3.3.3 U、V轴的安装与检测</a>';
tree+='<a href="../3_3_4/3_3_4.html">◆ 3.3.4 A轴的安装与检测</a>';
tree+='</div>';
tree+='</dd>';
tree+='<dd>';
tree+='<p>★ 3.4 直角坐标机器人电气系统的装配与调试</p>';
tree+='<div>';
tree+='<a href="../3_4_1/3_4_1.html">◆ 3.4.1 接线前的准备</a>';
tree+='<a href="../3_4_2/3_4_2.html">◆ 3.4.2 直角坐标机器人电气系统接线流程</a>';
tree+='</div>';
tree+='</dd>';
tree+='<dd>';
tree+='<p><a href="../3_5_1/3_5_1.html">★ 3.5 直角坐标机器人整机的安装与调试</a></p>';
tree+='<p><a href="../3_6_1/3_6_1.html">★ 章节测试</a></p>';
tree+='</dd>';
tree+='</dl>';
tree+='</li>';
tree+='<li class="tree-one">';
tree+='<p>四</p>';
tree+='<dl>';
tree+='<dt>第四章 六轴关节机器人的装配与调试</dt>';
tree+='<dd>';
tree+='<p><a href="../4_0_1/4_0_1.html">★ 本章导入</a></p>';
tree+='</dd>';
tree+='<dd>';
tree+='<p><a href="../4_1_1/4_1_1.html">★ 4.1 六轴关节机器人的简介</a></p>';
tree+='</dd>';
tree+='<dd>';
tree+='<p><a href="../4_2_1/4_2_1.html">★ 4.2 机械传动部分的装配与调试</a></p>';
tree+='</dd>';
tree+='<dd>';
tree+='<p>★ 4.3 六关节机器人的拆卸</p>';
tree+='<div>';
tree+='<a href="../4_3_1/4_3_1.html">◆ 4.3.1 本体各端盖、固定块、防撞块的拆卸</a>';
tree+='<a href="../4_3_2/4_3_2.html">◆ 4.3.2 第六、五、四轴的拆卸</a>';
tree+='<a href="../4_3_3/4_3_3.html">◆ 4.3.3 第三、二轴以及转座的拆卸</a>';
tree+='</div>';
tree+='</dd>';
tree+='<dd>';
tree+='<p>★ 4.4 六关节机器人的装配</p>';
tree+='<div>';
tree+='<a href="../4_4_1/4_4_1.html">◆ 4.4.1 转座及第二、三轴的安装</a>';
tree+='<a href="../4_4_2/4_4_2.html">◆ 4.4.2 第四、五、六轴的安装</a>';
tree+='</div>';
tree+='<dd>';
tree+='<p><a href="../4_5_1/4_5_1.html">★ 4.5 六关节机器人的整机安装与调试</a></p>';
tree+='</dd>';
tree+='<dd>';
tree+='<p><a href="../4_6_1/4_6_1.html">★ 章节测试</a></p>';
tree+='</dd>';
tree+='</dl>';
tree+='</li>';
tree+='<li class="tree-top hidden-xs"><a href="javascript:void(0)">TOP</a></li>';
tree+='</ul>';
tree+='</div>';
document.write(tree);                    
                                   
                                    
$(".tree-top a").click(function(){
	var top=$(window).scrollTop();
	var si=setInterval(function(){
		console.log(top);
		if(top<0){
			clearInterval(si);	
		}
		top-=10;
		$(window).scrollTop(top);
	},1);
});
                            
                            
                        
                    